Repository aramis-lab/clinica, pull requests merged in 2023-12, with the labels that each got.

#1038 Fix dwi positive direction in dwi-preprocessing
  clinica/utils/dwi.py
Labels: fix

#1032 MAINT: Use ruff for linting and formatting
  .pre-commit-config.yaml
  clinica/iotools/bids_utils.py
  clinica/pipelines/dwi_connectome/dwi_connectome_pipeline.py
  clinica/pipelines/dwi_dti/dwi_dti_pipeline.py
  clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_pipeline.py
  clinica/pipelines/machine_learning/algorithm.py
  clinica/pipelines/machine_learning/vertex_based_io.py
  clinica/pipelines/machine_learning_spatial_svm/spatial_svm_utils.py
  pyproject.toml
  test/unittests/pipelines/dwi_preprocessing_using_t1/test_dwi_preprocessing_using_t1_utils.py
  test/unittests/utils/test_freesurfer.py
Labels: enhancement

#1040 [CI] Run SPM based non regression tests in the same process
  .github/workflows/test_non_regression_fast.yml
Labels: CI

#1041 [ADNI] Allow convert fmri multiband
  clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmri.py
  clinica/iotools/converters/adni_to_bids/adni_to_bids.py
Labels: enhancement, converter

#1042 [DOC] Add entry in documentation for NOW 2023
  docs/ClinicaConferences.md
Labels: doc

#1043 Get rid of Niflow and unpin Nibabel
  clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fdg_pet.py
  clinica/iotools/converters/adni_to_bids/adni_modalities/adni_pib_pet.py
  clinica/iotools/converters/adni_to_bids/adni_modalities/adni_tau_pet.py
  clinica/iotools/converters/adni_to_bids/adni_utils.py
  clinica/iotools/utils/data_handling.py
  clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_utils.py
  clinica/pipelines/dwi_preprocessing_using_fmap/dwi_preprocessing_using_phasediff_fmap_workflows.py
  poetry.lock
  pyproject.toml
  test/unittests/utils/test_image.py
Labels: dependencies
