Repository aramis-lab/clinica, pull requests merged in 2024-05, with the labels that each got.

#1178 Fix logic in adni_utils by restoring loops in create_file
  clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmap.py
  clinica/iotools/converters/adni_to_bids/adni_utils.py
Labels: bug, converter

#1184 [FIX] Fix handlers addition to the clinica logger
  clinica/cmdline.py
Labels: fix

#1185 [FIX] Fix calls to `matplotlib.cm.get_cmap`
  clinica/pipelines/machine_learning/ml_utils.py
Labels: fix

#1191 [CI] Use Github Actions to build and deploy documentation
  .github/workflows/build_and_deploy.yml
  .jenkins/docs.Jenkinsfile
  .jenkins/scripts/find_env.sh
Labels: CI

#1192 [CI] Fix deployed documentation folder names
  .github/workflows/build_and_deploy.yml
Labels: CI

#1193 [CI] Fix wrong folder name when deploying doc
  .github/workflows/build_and_deploy.yml
Labels: CI

#1194 [CI] Fix typo in GitHub context variable in documentation deploy pipeline
  .github/workflows/build_and_deploy.yml
  .github/workflows/test_converters.yml
  .github/workflows/test_instantiation.yml
  .github/workflows/test_non_regression_fast.yml
  .github/workflows/test_pipelines_anat.yml
  .github/workflows/test_pipelines_anat_freesurfer.yml
  .github/workflows/test_pipelines_dwi.yml
  .github/workflows/test_pipelines_dwi_preprocessing.yml
  .github/workflows/test_pipelines_pet.yml
Labels: CI

#1190 [ENH] Proposition for adni-to-bids converter FMAP renaming
  clinica/iotools/bids_utils.py
  clinica/iotools/converters/adni_to_bids/adni_modalities/adni_fmap.py
  clinica/iotools/converters/adni_to_bids/adni_utils.py
  test/unittests/iotools/converters/adni_to_bids/adni_modalities/test_adni_fmap.py
Labels: enhancement, converter
