Repository aramis-lab/clinica, pull requests merged in 2024-08, with the labels that each got.

#1244 [ENH] Add the possibility to use `ANTsPy` instead of `ANTs` for `T1Linear` and `FlairLinear`
  clinica/pipelines/engine.py
  clinica/pipelines/t1_linear/anat_linear_pipeline.py
  clinica/pipelines/t1_linear/anat_linear_utils.py
  clinica/pipelines/t1_linear/flair_linear_cli.py
  clinica/pipelines/t1_linear/t1_linear_cli.py
  clinica/pipelines/t1_linear/tasks.py
  docs/Pipelines/FLAIR_Linear.md
  docs/Pipelines/T1_Linear.md
  poetry.lock
  pyproject.toml
  test/unittests/pipelines/t1_linear/test_anat_linear_utils.py
Labels: pipeline, dependencies

#1250 [MAINT] Remove upper bound constraint on `cattrs` version
  poetry.lock
  pyproject.toml
Labels: dependencies

#1158 [ENH] Implement dataset description for CAPS datasets
  clinica/iotools/bids_dataset_description.py
  clinica/pipelines/anatomical/freesurfer/t1/cli.py
  clinica/pipelines/cli_param/option.py
  clinica/pipelines/dwi/preprocessing/fmap/cli.py
  clinica/pipelines/dwi/preprocessing/t1/cli.py
  clinica/pipelines/engine.py
  clinica/pipelines/t1_linear/anat_linear_pipeline.py
  clinica/pipelines/t1_linear/flair_linear_cli.py
  clinica/pipelines/t1_linear/t1_linear_cli.py
  clinica/pipelines/t1_volume/t1_volume_cli.py
  clinica/pipelines/t1_volume_create_dartel/t1_volume_create_dartel_cli.py
  clinica/pipelines/t1_volume_dartel2mni/t1_volume_dartel2mni_cli.py
  clinica/pipelines/t1_volume_parcellation/t1_volume_parcellation_cli.py
  clinica/pipelines/t1_volume_register_dartel/t1_volume_register_dartel_cli.py
  clinica/pipelines/t1_volume_tissue_segmentation/t1_volume_tissue_segmentation_cli.py
  clinica/utils/bids.py
  clinica/utils/caps.py
  clinica/utils/inputs.py
  clinica/utils/testing_utils.py
  docs/CAPS/Introduction.md
  docs/CAPS/Specifications.md
  docs/Pipelines/DWI_Preprocessing.md
  docs/Pipelines/T1_FreeSurfer.md
  docs/Pipelines/T1_Linear.md
  docs/Pipelines/T1_Volume.md
  test/instantiation/test_instantiate_all_pipelines.py
  test/unittests/iotools/test_bids_utils.py
  test/unittests/pipelines/t1_linear/test_anat_linear_pipeline.py
  test/unittests/utils/test_caps.py
  test/unittests/utils/test_utils_inputs.py
Labels: enhancement

#1261 [FIX] Specify path to SPM when using Matlab and SPM12
  clinica/utils/spm.py
  test/unittests/pipelines/statistics_volume/test_statistics_volume_utils.py
  test/unittests/utils/test_spm.py
Labels: fix

#1271 [FIX] Fix bugs in data handling utilities
  clinica/iotools/converters/adni_to_bids/adni_utils.py
  clinica/iotools/utils/data_handling/_centering.py
  clinica/iotools/utils/data_handling/_merging.py
  clinica/iotools/utils/pipeline_handling.py
Labels: fix

#1272 [DOC] Modify `habs-to-bids` name in documentation title
  docs/Converters/HABS2BIDS.md
Labels: doc

#1266 [ENH] Add third-party software version getters
  clinica/utils/check_dependency.py
  test/unittests/utils/test_check_dependency.py
Labels: enhancement

#1239 [CONV] Implementing new converter for IXI dataset
  clinica/iotools/bids_utils.py
  clinica/iotools/converters/adni_to_bids/adni_utils.py
  clinica/iotools/converters/cli.py
  clinica/iotools/converters/factory.py
  clinica/iotools/converters/ixi_to_bids/__init__.py
  clinica/iotools/converters/ixi_to_bids/ixi_to_bids.py
  clinica/iotools/converters/ixi_to_bids/ixi_to_bids_cli.py
  clinica/iotools/converters/ixi_to_bids/ixi_to_bids_utils.py
  test/unittests/iotools/converters/ixi_to_bids/test_ixi_to_bids_utils.py
  test/unittests/iotools/test_bids_utils.py
Labels: converter
