Repository aramis-lab/clinica, pull requests merged in 2024-07, with the labels that each got.

#1219 [ENH] Improve tests for bids_utils
  clinica/iotools/bids_utils.py
  test/unittests/iotools/test_bids_utils.py
Labels: converter

#1221 [DOC] Clarify TSV file origin for PET Surface pipeline
  docs/Pipelines/PET_Surface.md
Labels: doc

#1220 [ENH] Proposition of a function to translate study ids to bids ids
  clinica/iotools/bids_utils.py
  clinica/iotools/converters/adni_to_bids/adni_json.py
  clinica/iotools/converters/adni_to_bids/adni_to_bids.py
  clinica/iotools/converters/adni_to_bids/adni_utils.py
  clinica/iotools/converters/aibl_to_bids/utils/bids.py
  clinica/iotools/converters/aibl_to_bids/utils/clinical.py
  clinica/iotools/converters/genfi_to_bids/genfi_to_bids_utils.py
  clinica/iotools/converters/habs_to_bids/habs_to_bids.py
  clinica/iotools/converters/nifd_to_bids/nifd_utils.py
  clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py
  clinica/iotools/converters/oasis_to_bids/oasis_to_bids.py
  clinica/iotools/converters/ukb_to_bids/ukb_utils.py
  test/unittests/iotools/converters/adni_to_bids/test_adni_json.py
  test/unittests/iotools/test_bids_utils.py
Labels: enhancement, converter

#1227 [FIX] Change check on type in converter NIFD
  clinica/iotools/converters/nifd_to_bids/nifd_utils.py
Labels: converter, fix

#1230 [FIX] Change check on type in converter NIFD
  clinica/iotools/converters/nifd_to_bids/nifd_utils.py
Labels: fix

#1169 [FIX] Fixes DWI preprocessing using T1 when images are 3D
  clinica/pipelines/dwi/preprocessing/t1/pipeline.py
  clinica/pipelines/dwi/preprocessing/t1/utils.py
  clinica/pipelines/dwi/preprocessing/utils.py
  clinica/pipelines/dwi/preprocessing/workflows.py
  clinica/pipelines/engine.py
  test/unittests/pipelines/dwi/preprocessing/test_t1_utils.py
Labels: fix

#1235 [FIX] Fix cross sectional to longitudinal conversion logic
  clinica/pipelines/engine.py
  test/unittests/pipelines/test_nipype_engine.py
Labels: fix

#1240 [FIX] Fix t1-freesurfer pipeline handler
  clinica/iotools/utils/data_handling.py
  clinica/iotools/utils/pipeline_handling.py
  test/unittests/iotools/utils/test_pipeline_handling.py
Labels: fix

#1242 [FIX] Fix broken import
  clinica/iotools/utils/pipeline_handling.py
Labels: fix

#1045 [REF TEST] Refactor data handling
  clinica/iotools/converters/adni_to_bids/adni_utils.py
  clinica/iotools/utils/data_handling/__init__.py
  clinica/iotools/utils/data_handling/_centering.py
  clinica/iotools/utils/data_handling/_files.py
  clinica/iotools/utils/data_handling/_merging.py
  clinica/iotools/utils/data_handling/_missing.py
  clinica/iotools/utils/pipeline_handling.py
  clinica/utils/exceptions.py
  clinica/utils/testing_utils.py
  test/unittests/iotools/utils/test_data_handling.py
  test/unittests/iotools/utils/test_pipeline_handling.py
Labels: enhancement
